# a yaml file to specify input to the pipline

# dirs
fastqdir:       "/home/jeremias/dev/macpipe_trans/data/"
transrateDir:   "/home/jeremias/dev/macpipe_trans/transrate/"
homedir:        "/home/jeremias/dev/macpipe_trans/"

# path to various softwares
adapters_fasta: "/home/jeremias/soft/Trimmomatic-0.36/adapters/Truseq_barcodes.fa"
py3:            "/home/jeremias/.linuxbrew/var/pyenv/versions/3.5.2/bin/python"

# path to the busco database    
BuscoLib:       "/home/jeremias/soft/busco/eukaryota_odb9"
# path to BUSCO executable
BUSCO:          "/home/jeremias/soft/busco/BUSCO.py"
# path to BUSCO.plotting function
BUSCO_p:        "/home/jeremias/soft/busco/BUSCO_plot.py"
