######################################
#
# BUSCO summary figure
# @author Mathieu Seppey <mathieu.seppey@unige.ch>
# @version 2.0
# @since BUSCO 2.0
# 
# Copyright (C) 2016 E. Zdobnov lab
# 
# BUSCO is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version. See <http://www.gnu.org/licenses/>
#  
# BUSCO is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
######################################

# Load the required libraries
library(ggplot2)
library("grid")
options(bitmapType="cairo")
# !!! CONFIGURE YOUR PLOT HERE !!! 
# Output
my_output <- paste("busco/summary/","busco_figure.png",sep="/") 
my_width <- 20
my_height <- 15
my_unit <- "cm"

# Colors
my_colors <- c("#56B4E9", "#3492C7", "#F0E442", "#F04442")
# Bar height ratio
my_bar_height <- 0.75

# Legend
my_title <- "BUSCO Assessment Results"

# Font
my_family <- "sans"
my_size_ratio <- 1

# !!! SEE YOUR DATA HERE !!! 
# Your data as generated by python, remove or add more
my_species <- c('Mpus_subset_50000000.good.busco', 'Mpus_subset_50000000.good.busco', 'Mpus_subset_50000000.good.busco', 'Mpus_subset_50000000.good.busco', 'Mpus_subset_100000000.busco', 'Mpus_subset_100000000.busco', 'Mpus_subset_100000000.busco', 'Mpus_subset_100000000.busco', 'Mhtx_subset_10000000.busco', 'Mhtx_subset_10000000.busco', 'Mhtx_subset_10000000.busco', 'Mhtx_subset_10000000.busco', 'Mhtx_subset_15000000.good.busco', 'Mhtx_subset_15000000.good.busco', 'Mhtx_subset_15000000.good.busco', 'Mhtx_subset_15000000.good.busco', 'Mpus_subset_130000000.busco', 'Mpus_subset_130000000.busco', 'Mpus_subset_130000000.busco', 'Mpus_subset_130000000.busco', 'Mcla_subset_10000000.busco', 'Mcla_subset_10000000.busco', 'Mcla_subset_10000000.busco', 'Mcla_subset_10000000.busco', 'Mspi_subset_15000000.busco', 'Mspi_subset_15000000.busco', 'Mspi_subset_15000000.busco', 'Mspi_subset_15000000.busco', 'Mspi_subset_10000000.busco', 'Mspi_subset_10000000.busco', 'Mspi_subset_10000000.busco', 'Mspi_subset_10000000.busco', 'Mspi_subset_10000000.good.busco', 'Mspi_subset_10000000.good.busco', 'Mspi_subset_10000000.good.busco', 'Mspi_subset_10000000.good.busco', 'Mcla_subset_15000000.good.busco', 'Mcla_subset_15000000.good.busco', 'Mcla_subset_15000000.good.busco', 'Mcla_subset_15000000.good.busco', 'Mspi_subset_50000000.busco', 'Mspi_subset_50000000.busco', 'Mspi_subset_50000000.busco', 'Mspi_subset_50000000.busco', 'Mspi_subset_15000000.good.busco', 'Mspi_subset_15000000.good.busco', 'Mspi_subset_15000000.good.busco', 'Mspi_subset_15000000.good.busco', 'Mhtx_subset_10000000.good.busco', 'Mhtx_subset_10000000.good.busco', 'Mhtx_subset_10000000.good.busco', 'Mhtx_subset_10000000.good.busco', 'Mhtx_subset_50000000.busco', 'Mhtx_subset_50000000.busco', 'Mhtx_subset_50000000.busco', 'Mhtx_subset_50000000.busco', 'Mcla_subset_10000000.good.busco', 'Mcla_subset_10000000.good.busco', 'Mcla_subset_10000000.good.busco', 'Mcla_subset_10000000.good.busco', 'Mhtx_subset_15000000.busco', 'Mhtx_subset_15000000.busco', 'Mhtx_subset_15000000.busco', 'Mhtx_subset_15000000.busco', 'Mcla_subset_15000000.busco', 'Mcla_subset_15000000.busco', 'Mcla_subset_15000000.busco', 'Mcla_subset_15000000.busco', 'Mpus_subset_130000000.good.busco', 'Mpus_subset_130000000.good.busco', 'Mpus_subset_130000000.good.busco', 'Mpus_subset_130000000.good.busco', 'Mpus_subset_10000000.good.busco', 'Mpus_subset_10000000.good.busco', 'Mpus_subset_10000000.good.busco', 'Mpus_subset_10000000.good.busco', 'Mpus_subset_10000000.busco', 'Mpus_subset_10000000.busco', 'Mpus_subset_10000000.busco', 'Mpus_subset_10000000.busco', 'Mhtx_subset_50000000.good.busco', 'Mhtx_subset_50000000.good.busco', 'Mhtx_subset_50000000.good.busco', 'Mhtx_subset_50000000.good.busco', 'Mpus_subset_100000000.good.busco', 'Mpus_subset_100000000.good.busco', 'Mpus_subset_100000000.good.busco', 'Mpus_subset_100000000.good.busco', 'Mpus_subset_15000000.busco', 'Mpus_subset_15000000.busco', 'Mpus_subset_15000000.busco', 'Mpus_subset_15000000.busco', 'Mhtx_subset_100000000.busco', 'Mhtx_subset_100000000.busco', 'Mhtx_subset_100000000.busco', 'Mhtx_subset_100000000.busco', 'Mpus_subset_15000000.good.busco', 'Mpus_subset_15000000.good.busco', 'Mpus_subset_15000000.good.busco', 'Mpus_subset_15000000.good.busco', 'Mspi_subset_100000000.good.busco', 'Mspi_subset_100000000.good.busco', 'Mspi_subset_100000000.good.busco', 'Mspi_subset_100000000.good.busco', 'Mspi_subset_130000000.good.busco', 'Mspi_subset_130000000.good.busco', 'Mspi_subset_130000000.good.busco', 'Mspi_subset_130000000.good.busco', 'Mhtx_subset_100000000.good.busco', 'Mhtx_subset_100000000.good.busco', 'Mhtx_subset_100000000.good.busco', 'Mhtx_subset_100000000.good.busco', 'Mspi_subset_100000000.busco', 'Mspi_subset_100000000.busco', 'Mspi_subset_100000000.busco', 'Mspi_subset_100000000.busco', 'Mspi_subset_50000000.good.busco', 'Mspi_subset_50000000.good.busco', 'Mspi_subset_50000000.good.busco', 'Mspi_subset_50000000.good.busco', 'Mspi_subset_130000000.busco', 'Mspi_subset_130000000.busco', 'Mspi_subset_130000000.busco', 'Mspi_subset_130000000.busco', 'Mpus_subset_50000000.busco', 'Mpus_subset_50000000.busco', 'Mpus_subset_50000000.busco', 'Mpus_subset_50000000.busco')
my_species <- factor(my_species)
my_species <- factor(my_species,levels(my_species)[c(length(levels(my_species)):1)]) # reorder your species here just by changing the values in the vector :
my_percentage <- c(71.9, 16.2, 4.6, 7.3, 72.3, 22.8, 4.3, 0.6, 49.8, 12.9, 29.0, 8.3, 58.4, 15.2, 22.4, 4.0, 71.3, 24.4, 3.6, 0.7, 56.1, 24.8, 16.2, 2.9, 75.2, 20.5, 3.0, 1.3, 79.2, 13.5, 5.3, 2.0, 78.2, 11.9, 5.3, 4.6, 57.4, 26.4, 11.9, 4.3, 72.6, 25.4, 1.0, 1.0, 76.2, 16.2, 3.0, 4.6, 50.5, 12.2, 29.0, 8.3, 65.3, 23.8, 8.9, 2.0, 57.8, 22.8, 16.2, 3.2, 58.1, 15.5, 22.8, 3.6, 57.1, 28.4, 12.2, 2.3, 69.0, 20.5, 4.6, 5.9, 76.9, 12.9, 7.3, 2.9, 77.9, 14.2, 7.3, 0.6, 66.0, 23.1, 8.9, 2.0, 71.0, 19.5, 4.3, 5.2, 80.5, 14.5, 4.3, 0.7, 64.4, 28.7, 5.3, 1.6, 79.9, 13.9, 4.3, 1.9, 67.7, 28.4, 1.0, 2.9, 62.7, 31.0, 1.3, 5.0, 63.4, 28.1, 5.3, 3.2, 67.7, 30.4, 1.0, 0.9, 72.9, 20.5, 1.0, 5.6, 63.4, 34.3, 1.0, 1.3, 75.6, 19.5, 4.3, 0.6)
my_values <- c()

######################################
######################################
######################################
# Code to produce the graph
labsize = 1
if (length(levels(my_species)) > 10){
 labsize = 0.66
}
print("Plotting the figure ...")
category <- c(rep(c("S","D","F","M"),c(1)))
category <-factor(category)
category = factor(category,levels(category)[c(4,1,2,3)])
df = data.frame(my_species,my_percentage,my_values,category)

figure <- ggplot() + 
  
  geom_bar(aes(y = my_percentage, x = my_species, fill = category), data = df, stat="identity", width=my_bar_height) + 
  coord_flip() + 
  theme_gray(base_size = 8) + 
  scale_y_continuous(labels = c("0","20","40","60","80","100"), breaks = c(0,20,40,60,80,100)) + 
  scale_fill_manual(values = my_colors,labels =c(" Complete (C) and single-copy (S)  ",
                                                 " Complete (C) and duplicated (D)",
                                                 " Fragmented (F)  ",
                                                 " Missing (M)")) +   
  ggtitle(my_title) + 
  xlab("") + 
  ylab("\n%BUSCOs") + 

  theme(plot.title = element_text(family=my_family, colour = "black", size = rel(2.2)*my_size_ratio, face = "bold")) + 
  theme(legend.position="top",legend.title = element_blank()) + 
  theme(legend.text = element_text(family=my_family, size = rel(1.2)*my_size_ratio)) + 
  theme(panel.background = element_rect(color="#FFFFFF", fill="white")) + 
  theme(panel.grid.minor = element_blank()) + 
  theme(panel.grid.major = element_blank()) +
  theme(axis.text.y = element_text(family=my_family, colour = "black", size = rel(1.66)*my_size_ratio)) + 
  theme(axis.text.x = element_text(family=my_family, colour = "black", size = rel(1.66)*my_size_ratio)) + 
  theme(axis.line = element_line(size=1*my_size_ratio, colour = "black")) + 
  theme(axis.ticks.length = unit(.85, "cm")) + 
  theme(axis.ticks.y = element_line(colour="white", size = 0)) + 
  theme(axis.ticks.x = element_line(colour="#222222")) + 
  theme(axis.ticks.length = unit(0.4, "cm")) + 
  theme(axis.title.x = element_text(family=my_family, size=rel(1.2)*my_size_ratio)) + 
  
  guides(fill = guide_legend(override.aes = list(colour = NULL))) +
  guides(fill=guide_legend(nrow=2,byrow=TRUE))
  
  for(i in rev(c(1:length(levels(my_species))))){
    detailed_values <- my_values[my_species==my_species[my_species==levels(my_species)[i]]]
    total_buscos <- sum(detailed_values)
    figure <- figure + 
    annotate("text", label=paste("C:", detailed_values[1] + detailed_values[2], " [S:", detailed_values[1], ", D:", detailed_values[2], "], F:", detailed_values[3], ", M:", detailed_values[4], ", n:", total_buscos, sep=""), 
             y=3, x = i, size = labsize*4*my_size_ratio, colour = "black", hjust=0, family=my_family)
  }
  
ggsave(figure, file="test.png", width = my_width, height = my_height, unit = my_unit)
print("Done")
